INSERT INTO BUSES (BUS_NUMBER, CAPACITY) VALUES ('BUS-101', 50);
INSERT INTO BUSES (BUS_NUMBER, CAPACITY) VALUES ('BUS-102', 45);
INSERT INTO BUSES (BUS_NUMBER, CAPACITY) VALUES ('BUS-103', 40);
INSERT INTO BUSES (BUS_NUMBER, CAPACITY) VALUES ('BUS-104', 50);

INSERT INTO PASSENGERS (FULL_NAME) VALUES ('Aruzhan Nur');
INSERT INTO PASSENGERS (FULL_NAME) VALUES ('Daniyar Sadu');
INSERT INTO PASSENGERS (FULL_NAME) VALUES ('Almanzor Kamzeyev');

INSERT INTO TRANSPORT_SERVICES (BUS_ID, PASSENGER_ID, FROM_LOCATION, TO_LOCATION, DEPARTURE_TIME)
VALUES (1, 1, 'Astana', 'Taraz', '2026-02-10T09:30:00');

INSERT INTO TRANSPORT_SERVICES (BUS_ID, PASSENGER_ID, FROM_LOCATION, TO_LOCATION, DEPARTURE_TIME)
VALUES (2, 2, 'Almaty', 'Shymkent', '2026-02-11T11:45:00');

INSERT INTO TRANSPORT_SERVICES (BUS_ID, PASSENGER_ID,  FROM_LOCATION, TO_LOCATION, DEPARTURE_TIME)
VALUES (4, 3,'Uralsk', 'Astana', '2026-02-12T14:00:00');